// Script to generate config.js from .env file
// Run: node generate-config.js
// Compatible with older Node.js versions (ES5 syntax)

var fs = require('fs');
var path = require('path');

var configPath = path.join(__dirname, 'js', 'config.js');
var envPath = path.join(__dirname, '.env');

// Check if .env file exists
if (!fs.existsSync(envPath)) {
    process.exit(1);
}

// Read and parse .env file manually (no dotenv dependency needed)
function parseEnvFile(filePath) {
    var envContent = fs.readFileSync(filePath, 'utf8');
    var envVars = {};
    var lines = envContent.split('\n');
    
    for (var i = 0; i < lines.length; i++) {
        var line = lines[i].trim();
        
        // Remove comments and empty lines
        if (!line || line.indexOf('#') === 0) {
            continue;
        }
        
        // Parse KEY=VALUE format
        var equalIndex = line.indexOf('=');
        if (equalIndex > 0) {
            var key = line.substring(0, equalIndex).trim();
            var value = line.substring(equalIndex + 1).trim();
            
            // Remove quotes if present
            if ((value.indexOf('"') === 0 && value.lastIndexOf('"') === value.length - 1) ||
                (value.indexOf("'") === 0 && value.lastIndexOf("'") === value.length - 1)) {
                value = value.substring(1, value.length - 1);
            }
            
            envVars[key] = value;
        }
    }
    
    return envVars;
}

// Read values from .env
var envVars = parseEnvFile(envPath);
var telegramBotToken = envVars.TELEGRAM_BOT_TOKEN || '';
var telegramChatId = envVars.TELEGRAM_CHAT_ID || '';
var telegramChannelUrl = envVars.TELEGRAM_CHANNEL_URL || 'https://t.me/kinetraX';
var twitterUrl = envVars.TWITTER_URL || 'https://x.com/kinetrax';

// Validate required values
if (!telegramBotToken || !telegramChatId) {
    process.exit(1);
}

// Escape JavaScript string values to prevent injection
function escapeJsString(str) {
    return String(str)
        .replace(/\\/g, '\\\\')
        .replace(/'/g, "\\'")
        .replace(/\n/g, '\\n')
        .replace(/\r/g, '\\r')
        .replace(/\t/g, '\\t');
}

// Generate config.js content
var configContent = '// Auto-generated config file from .env\n' +
    '// DO NOT EDIT THIS FILE MANUALLY - it will be overwritten\n' +
    '// Edit .env file and run: node generate-config.js\n\n' +
    'window.PRESALE_CONFIG = {\n' +
    '    telegramBotToken: \'' + escapeJsString(telegramBotToken) + '\',\n' +
    '    telegramChatId: \'' + escapeJsString(telegramChatId) + '\',\n' +
    '    telegramChannelUrl: \'' + escapeJsString(telegramChannelUrl) + '\',\n' +
    '    twitterUrl: \'' + escapeJsString(twitterUrl) + '\'\n' +
    '};\n';

// Write config.js
try {
    fs.writeFileSync(configPath, configContent, 'utf8');
} catch (error) {
    process.exit(1);
}
