// Script to generate config.js from .env file
// Run: node generate-config.js
// Compatible with older Node.js versions (ES5 syntax)

var fs = require('fs');
var path = require('path');

var configPath = path.join(__dirname, 'js', 'config.js');
var envPath = path.join(__dirname, '.env');

// Read values from environment variables (Netlify) or .env file (local)
// Note: telegramBotToken and telegramChatId are no longer exposed to frontend
// They are used server-side only via Netlify functions
var telegramBotUsername = '';
var telegramChannelUrl = 'https://t.me/kinetraX';
var twitterUrl = 'https://x.com/kinetrax';
var recaptchaSiteKey = '';

// Check if running on Netlify (environment variables available)
if (process.env.TELEGRAM_BOT_USERNAME || process.env.RECAPTCHA_SITE_KEY) {
    // Use Netlify environment variables
    // Note: TELEGRAM_BOT_TOKEN and TELEGRAM_CHAT_ID are NOT exposed to frontend
    // They are used server-side only via Netlify functions
    telegramBotUsername = process.env.TELEGRAM_BOT_USERNAME || '';
    telegramChannelUrl = process.env.TELEGRAM_CHANNEL_URL || 'https://t.me/kinetraX';
    twitterUrl = process.env.TWITTER_URL || 'https://x.com/kinetrax';
    recaptchaSiteKey = process.env.RECAPTCHA_SITE_KEY || '';
} else if (fs.existsSync(envPath)) {
    // Fallback to .env file for local development
    function parseEnvFile(filePath) {
        var envContent = fs.readFileSync(filePath, 'utf8');
        var envVars = {};
        var lines = envContent.split('\n');
        
        for (var i = 0; i < lines.length; i++) {
            var line = lines[i].trim();
            
            // Remove comments and empty lines
            if (!line || line.indexOf('#') === 0) {
                continue;
            }
            
            // Parse KEY=VALUE format
            var equalIndex = line.indexOf('=');
            if (equalIndex > 0) {
                var key = line.substring(0, equalIndex).trim();
                var value = line.substring(equalIndex + 1).trim();
                
                // Remove quotes if present
                if ((value.indexOf('"') === 0 && value.lastIndexOf('"') === value.length - 1) ||
                    (value.indexOf("'") === 0 && value.lastIndexOf("'") === value.length - 1)) {
                    value = value.substring(1, value.length - 1);
                }
                
                envVars[key] = value;
            }
        }
        
        return envVars;
    }
    
    var envVars = parseEnvFile(envPath);
    // Note: TELEGRAM_BOT_TOKEN and TELEGRAM_CHAT_ID are NOT exposed to frontend
    // They are used server-side only via Netlify functions
    telegramBotUsername = envVars.TELEGRAM_BOT_USERNAME || '';
    telegramChannelUrl = envVars.TELEGRAM_CHANNEL_URL || 'https://t.me/kinetraX';
    twitterUrl = envVars.TWITTER_URL || 'https://x.com/kinetrax';
    recaptchaSiteKey = envVars.RECAPTCHA_SITE_KEY || '';
}

// Note: TELEGRAM_BOT_TOKEN and TELEGRAM_CHAT_ID are now server-side only
// They are used in Netlify functions, not exposed to frontend
// No need to validate them here as they're not in the config

// Escape JavaScript string values to prevent injection
function escapeJsString(str) {
    return String(str)
        .replace(/\\/g, '\\\\')
        .replace(/'/g, "\\'")
        .replace(/\n/g, '\\n')
        .replace(/\r/g, '\\r')
        .replace(/\t/g, '\\t');
}

// Generate config.js content
var configContent = '// Auto-generated config file from .env\n' +
    '// DO NOT EDIT THIS FILE MANUALLY - it will be overwritten\n' +
    '// Edit .env file and run: node generate-config.js\n\n' +
    '// Note: TELEGRAM_BOT_TOKEN and TELEGRAM_CHAT_ID are no longer exposed here\n' +
    '// They are used server-side only via Netlify functions for security\n' +
    'window.PRESALE_CONFIG = {\n' +
    '    telegramBotUsername: \'' + escapeJsString(telegramBotUsername) + '\',\n' +
    '    telegramChannelUrl: \'' + escapeJsString(telegramChannelUrl) + '\',\n' +
    '    twitterUrl: \'' + escapeJsString(twitterUrl) + '\',\n' +
    '    recaptchaSiteKey: \'' + escapeJsString(recaptchaSiteKey) + '\'\n' +
    '};\n';

// Write config.js
try {
    fs.writeFileSync(configPath, configContent, 'utf8');
} catch (error) {
    process.exit(1);
}
